name: money_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  url_launcher: ^6.1.4
  dio: ^4.0.6
  equatable: ^2.0.3
  path_provider: ^2.0.11
  hive: ^2.2.3
  sembast: ^3.2.0+1
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.55.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/